name: Node CI

on:
  push:
    branches:
    - vue

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: npm install, build, and test
      run: |
        yarn install
        yarn build
    - uses: peaceiris/actions-gh-pages@v3
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
